---
- hosts: all
  become: yes

  tasks:
  - name: Update APT package manager repositories cache
    apt:
      update_cache: yes

  - name: Install OpenJDK Java
    apt:
      name: "{{ item }}"
      state: present
    with_items:
     openjdk-8-jdk
    
  - name: install maven on your local Ubuntu machine  
    apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
    with_items:
      - maven
      
  - name: install git  
    apt: 
      name: git
      state: present
      update_cache: yes

