# from galaxy
- name: geerlingguy.git

# from galaxy
#- name: yatesr.timezone

# from GitHub
#- src: https://github.com/bennojoy/nginx

# from GitHub, overriding the name and specifying a specific tag
#- name: nginx_role
#  src: https://github.com/bennojoy/nginx
#  version: master

# from a webserver, where the role is packaged in a tar.gz
#- name: http-role-gz
#  src: https://some.webserver.example.com/files/master.tar.gz

# from a webserver, where the role is packaged in a tar.bz2
#- name: http-role-bz2
#  src: https://some.webserver.example.com/files/master.tar.bz2

# from a webserver, where the role is packaged in a tar.xz (Python 3.x only)
#- name: http-role-xz
#  src: https://some.webserver.example.com/files/master.tar.xz

# from Bitbucket
#- src: git+https://bitbucket.org/willthames/git-ansible-galaxy
#  version: v1.4

# from Bitbucket, alternative syntax and caveats
#- src: https://bitbucket.org/willthames/hg-ansible-galaxy
#  scm: hg
